# Generated by Django 5.0.4 on 2024-04-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_proce', models.FloatField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('CPU', 'Procesador'), ('GPU', 'Tarjeta Grafica'), ('MB', 'Tarjeta Madre'), ('RAM', 'Memoria RAM'), ('SSD', 'Almacenamiento')], max_length=3)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
